[env:seeed_xiao]
platform = atmelsam
board = seeed_xiao
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit NeoPixel@~1.15.0
build_flags =
    -DUSBCON            ; el core de Seeed lo necesita para activar USB/PluggableUSB
    -DKEM_DEBUG=1       ; trazas por USB-CDC (quitar en producción)
